name: Release x64

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  call-build:
    uses: ./.github/workflows/build-webhapps.yml
    secrets: inherit

  # upload the artifacts
  upload-assets:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@v3
        with:
          name: all-happ-artifact
          path: artifacts
      # Display artifacts folder
      - name: Display artifacts folder
        run: ls
        working-directory: artifacts
      # upload all artifacts
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: artifacts
        run: |
          rm -f *.blockmap         
          echo threads*
          gh release upload "${GITHUB_REF#refs/tags/}" threads* --clobber
          echo profiles*
          gh release upload "${GITHUB_REF#refs/tags/}" profiles_zome.wasm --clobber          
          gh release upload "${GITHUB_REF#refs/tags/}" profiles_integrity_zome.wasm --clobber
